// client/src/pages/SignIn/SignIn.jsx
function SignIn() {
  return (
    <main className="main bg-dark">
      <section className="sign-in-content">
        <i className="fa fa-user-circle sign-in-icon"></i>
        <h1>Sign In</h1>
        <form>
          <div className="input-wrapper">
            <label for="username">Username</label>
            <input type="text" id="username" />
          </div>
          <div className="input-wrapper">
            <label for="password">Password</label>
            <input type="password" id="password" />
          </div>
          <div className="input-remember">
            <input type="checkbox" id="remember-me" />
            <label for="remember-me">Remember me</label>
          </div>
          <button className="sign-in-button">Sign In</button>
        </form>
      </section>
    </main>
  );
}

export default SignIn;

// designs/src/views/SignIn.vue
<script>
export default {
  methods: {
    signIn() {
      this.$router.push('/user')
    }
  }
}
</script>

<template>
  <main>
    <h1>Sign In</h1>
    <form>
      <label for="username">Username</label>
      <input type="text" id="username" />
      <label for="password">Password</label>
      <input type="password" id="password" />
      <input type="checkbox" id="remember-me" />
      <label for="remember-me">Remember me</label>
      <button @click.prevent="signIn">Sign In</button>
    </form>
  </main>
</template>

<style></style>
